server:
  port: 8083

spring:
  application:
    name: notification-service

entrypoint:
  sqs:
    region: ${AWS_REGION:us-east-1}
    queueUrl: ${QUEUE_URL}
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 30
    numberOfThreads: 1

aws:
  ses:
    region: ${AWS_REGION:us-east-1}
    sourceEmail: ${AWS_SES_SOURCE_EMAIL}
